storage:
    dbPath: "/data/db"
    journal:
        enabled: true

systemLog:
    destination: file
    path: "/data/db/mongod.log"
    logAppend: true

net:
    bindIp: 127.0.0.1
    port: 27017

replication:
   replSetName: ClueReplicaSet

