echo "ClueAnalytics Dev Env help"
echo "\tmake list"
echo "\t\tList all targets"
echo "\tmake list"
echo "\t\tList all targets"
echo "\tlist-all"
echo "\t\tList all targets with dependencies"
echo "\thelp"
echo "\t\tDisplay this screen" 
echo "\tbuild-clue-dependencies"
echo "\t\tBuild dependencies for all services into a docker image " 
echo "\tbuild-authenticator"
echo "\t\tBuild authenticator docker image" 
echo "\tbuild-orchestrator"
echo "\t\tBuild orchestrator docker image" 
echo "\tbuild-globalizer"
echo "\t\tBuild globalizer docker image" 
echo "\tbuild-mailer"
echo "\t\tBuild mailer docker image" 
echo "\tbuild-logger"
echo "\t\tBuild logger docker image" 
echo "\tbuild-scheduler"
echo "\t\tBuild scheduler docker image" 
echo "\tbuild-connection-tester"
echo "\t\tBuild connection-tester docker image" 
echo "\tbuild-dataset-controller"
echo "\t\tBuild dataset-controller docker image" 
echo "\tbuild-metadata-coordinator"
echo "\t\tBuild metadata-coordinator docker image" 
echo "\tbuild-metadata-importer"
echo "\t\tBuild metadata-importer docker image" 
echo "\tbuild-query-executor"
echo "\t\tBuild query-executor docker image" 
echo "\tbuild-query-generator"
echo "\t\tBuild query-generator docker image" 
echo "\build-dev-image"
echo "\t\tBuild development image"
echo "\tbuild-services"
echo "\t\tBuild all microservices docker images" 
echo "\tbuild-catalog"
echo "\t\tBuild clue-catalog images"
echo "\tbuild-dataset-store"
echo "\t\tBuild dataset store images"
echo "\tbuild-dfs"
echo "\t\tBuild seaweed dfs images"
echo "\tbuild-all"
echo "\t\tBuild a full cluster"
echo "\tclean-all"
echo "\t\tClean all images and containers"
echo "\tclean-local-cluster-data"
echo "\t\tClean local data from clue catalog and dataset store"
echo "\tstart-postgres"
echo "\t\t Start a postgres instance and install sample data"
echo "\tstart-oracle"
echo "\t\t Start an Oracle instance and install samples data"
echo "\tstart-databases"
echo "\t\tStart containers for all supported data sources"
echo "\tstop-postgres"
echo "\t\t Stop postgres instance"
echo "\tstop-oracle"
echo "\t\t Stop Oracle instance "
echo "\tstop-databases"
echo "\t\tStops all local supported data sources containers"
echo "\tcluster-start"
echo "\t\tStart a local cluster - all containers"
echo "\tcluster-stop"
echo "\t\tStops the local cluster - all containers"
echo "\tbuild-redis"
echo "\t\tBuild redis session store (clue-session-store)"
echo "\stop-<service-name>"
echo "\t\tStops a running docker service"
echo "\start-<service-name>"
echo "\t\tStarts docker service"
echo "\reload-<service-name>"
echo "\t\tStops and then starts docker service"
