FROM clueanalytics/dependencies

WORKDIR /home/src/authenticator

COPY package.json ./
COPY tsconfig*.json ./
COPY nodemon.json ./


RUN npm install

COPY . ./

RUN rm -fr /home/src/authentication-module/ \
    /home/src/catalog-module/ \
    /home/src/clue-dfs-module/ \
    /home/src/connection-test-module/ \
    /home/src/connection-tracking-module/ \
    /home/src/database-module/ \
    /home/src/datasets-controller-module/ \
    /home/src/graph-data-structure/ \
    /home/src/mail-module/ \
    /home/src/metadata-coordination-module/ \
    /home/src/metadata-importing-module/ \
    /home/src/query-executor-module/ \
    /home/src/query-generator-module/ \
    /home/src/scheduler-module/ \
    /home/src/metadata-importer/metadata-mapping/


EXPOSE 8260
CMD ["npm","start"]