FROM clueanalytics/dependencies

WORKDIR /home/src/metadata-importer

COPY package.json ./
COPY tsconfig*.json ./
COPY nodemon.json ./

RUN npm install

COPY . ./
RUN rm -Rf databases/macos/

RUN rm -fr /home/src/catalog-module/ \
    /home/src/clue-dfs-module/ \
    /home/src/connection-test-module/ \
    /home/src/connection-tracking-module/ \
    /home/src/datasets-controller-module/ \
    /home/src/globalization-module/ \
    /home/src/graph-data-structure/ \
    /home/src/mail-module/ \
    /home/src/metadata-coordination-module/ \
    /home/src/metadata-importing-module/ \
    /home/src/query-executor-module/ \
    /home/src/query-generator-module/ \
    /home/src/scheduler-module/

EXPOSE 8360
CMD ["npm","start"]
