# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./samples:/samples
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080